# Numpy
El módulo NumPy proporciona un objeto ndarray que podemos usar para realizar operaciones en una arreglo de cualquier dimensión. El ndarray significa arreglo de N dimensiones donde N es cualquier número. Eso significa que los arreglos NumPy puede ser de cualquier dimensión.

NumPy tiene una serie de ventajas sobre las listas de Python. Podemos realizar operaciones de alto rendimiento en los arreglos NumPy, tales como:

* Ordenar los miembros de un arreglo.
* Operaciones matemáticas y lógicas.
* Funciones de entrada / salida.
* Operaciones estadísticas y de álgebra lineal.

La razón por la que es tan usada hoy en día con respecto a las listas normales de Python aparte de lo anterior mensionado son:
* Las estructuras de Numpy ocupan menos espacio que las estructuras nativas de Python
* Las operaciones se hacen de forma más rápida que con las estructuras nativas de Python.

## Importamos la biblioteca

In [57]:
import numpy as np
import sys
import time

## Creación de un array
Para crear un nuevo array de Python partiremos de tener una lista creada

In [58]:
listaNumeros=[1,2,3,4,5]
a=np.array(listaNumeros)
print("Array creado:")
a

Array creado:


array([1, 2, 3, 4, 5])

Para verificar su tipo de dato usaremos la función type()

In [59]:
type(a)

numpy.ndarray

## Principales atributos del array
* dtype: Tipo de objetos que contiene el array
* itemsize: Número de elementos del array
* ndim: número de dimensiones del array

In [60]:
a = np.array([2, 4, 6,7])
print(a)
print(a.dtype)
print(a.itemsize)
print(a.ndim)
print("Bytes size: {} bytes".format(a.size * a.itemsize))

[2 4 6 7]
int32
4
1
Bytes size: 16 bytes


## arange()
La función arange genera una serie de números consecutivos entre ciertos límites
Por ejemplo:

In [61]:
print(np.arange(1,10))

[1 2 3 4 5 6 7 8 9]


### Ejercicio:
Generar un array que contenga los valores entre 0 y 99.
Imprimir el array generado

In [62]:
b=np.arange(0,100)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


## zeros()
Genera un número especifico de ceros.
Ejemplo:

In [63]:
print(np.zeros(8))

[0. 0. 0. 0. 0. 0. 0. 0.]


### Ejercicio:
Generar un array que contenga 20 ceros.
Imprimir el array generado

In [64]:
b=np.zeros(20)
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## full()

Genera una matriz con un número constante. Ejemplo:

In [65]:
constN=np.full((3,3),9)
print(constN)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


## random
Generación de números random

In [66]:
v = np.random.rand(4)
print(v)

[0.34493801 0.7935284  0.91799698 0.96764206]


## reshape
Numpy nos permite redimensionar los arreglos creados. Para ello usamos reshape()

In [67]:
nArr=np.random.choice([1,2,3,4,0],25)
print(nArr)
print(nArr.shape)
nArr55=nArr.reshape(5,5)
print(nArr55)
print(nArr55.shape)

[0 1 2 0 1 0 2 1 1 1 0 2 0 2 0 0 1 0 4 2 4 1 2 1 4]
(25,)
[[0 1 2 0 1]
 [0 2 1 1 1]
 [0 2 0 2 0]
 [0 1 0 4 2]
 [4 1 2 1 4]]
(5, 5)


## Acceder a los elementos
- Obtener una fila completa

In [76]:
print(nArr55[2])

[0 2 0 2 0]


- Obtener un elemento específico

In [77]:
print(nArr55[2,2])

0


- Uso de ":"

In [89]:
print(nArr55[:,2:5])

[[2 0 1]
 [1 1 1]
 [0 2 0]
 [0 4 2]
 [2 1 4]]


## Operaciones álgebra lineal

In [68]:
A=np.ones(9).reshape(3,3)
B=np.arange(10,19).reshape(3,3)
print("A:{}".format(A))
print()
print("B:{}".format(B))
print()

A:[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

B:[[10 11 12]
 [13 14 15]
 [16 17 18]]



- Suma: +

In [69]:
C=A+B
print("El resutado de la suma es:\n{}".format(C))

El resutado de la suma es:
[[11. 12. 13.]
 [14. 15. 16.]
 [17. 18. 19.]]


- Producto por escalar: n*Array

In [70]:
D=3*A
print("El resutado del producto por un escalar es:\n{}".format(D))

El resutado del producto por un escalar es:
[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


- Producto elemento a elemento: Array1*Array2

In [71]:
E=D*B
print("El resutado del producto elemento a elemento es:\n{}".format(E))

El resutado del producto elemento a elemento es:
[[30. 33. 36.]
 [39. 42. 45.]
 [48. 51. 54.]]


- Producto matricial: Array1 @ Array2

In [72]:
F=E@B
print("El resutado de la suma es:\n{}".format(F))

El resutado de la suma es:
[[1305. 1404. 1503.]
 [1656. 1782. 1908.]
 [2007. 2160. 2313.]]


## Ejercicio:
Dada la lista [12,15,19,60,80,10,9,0,9]
- Crea una matriz de 3x3 a partir de dicha lista y guárdala en "A"
- Crea una matriz de 3x3 rellenada con 7s y guárdala en "B"
- Crea una matriz de 3x3 que contenga elementos del 10 al 19 y guárdala en "C"
- Obten el producto matricial de A y B y almacénalo en "D"
- Suma las matrices C y D y guárdala en "E"
- Multiplica "E" por 10(escalar) y guárdala en "F"
- Muestra todas las filas y los valores a partir de la columna 1

In [94]:
lista=[12,15,19,60,80,10,9,0,9]
A=np.array(lista).reshape(3,3)
B=np.full((3,3),7)
C=np.arange(10,19).reshape(3,3)
D=A@B
E=D+C
F=10*E
print("El resultado es:\n{}".format(F[:,1:]))

El resultado es:
[[ 3330  3340]
 [10640 10650]
 [ 1430  1440]]
